data:
  train_files: ./examples/diffusion_data/video/data.jsonl
  val_files: ./examples/diffusion_data/video/val_data.jsonl
  prompt_key: text
  answer_key: answer
  image_key: images
  image_dir: null
  max_prompt_length: 2048
  max_response_length: 2048
  rollout_batch_size: 1  # equivalent to verl's data.train_batch_size
  mini_rollout_batch_size: null  # equivalent to verl's data.gen_batch_size
  val_batch_size: 1
  format_prompt: ./examples/format_prompt/math.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: false
  diffusion: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: flow_grpo

  kl_coef: 1.0e-2
  online_filtering: false  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99

worker:
  actor:
    global_batch_size: 1  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 1  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 1  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    ulysses_size: 1
    diffusion: true
    kl_penalty: flow_grpo
    loss_avg_mode: seq
    guidance_scale: 4.5
    model:
      model_path: stabilityai/stable-diffusion-3.5-medium
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      use_orig_params: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 2
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    limit_images: 0
    val_override_config:
      temperature: 0.5
      n: 1
    diffusion: true
    guidance_scale: 4.5
    resolution: 768
    num_steps: 4
    kl_reward: 0.0
    num_frames: 17
    height: 256
    width: 256

  ref:
    ulysses_size: 1
    diffusion: true
    guidance_scale: 4.5
    scheduler: Wan-AI/Wan2.1-T2V-1.3B-Diffusers
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
      use_orig_params: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/diffusion.py:compute_score
    diffusion: true

trainer:
  total_epochs: 15
  max_steps: null
  project_name: easy_r1
  experiment_name: wan2_1_t2v_1.3b_grpo
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20  # -1 means no limit
  val_freq: -1 # -1 to disable
  val_before_train: false
  val_only: false
  val_generations_to_log: 3
  save_freq: 1  # -1 to disable
  save_limit: 3  # -1 to disable
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  diffusion: true
